name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    # Configure Gradle for optimal use in GitHub Actions, including caching of downloaded dependencies.
    # See: https://github.com/gradle/actions/blob/main/setup-gradle/README.md
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3

    - name: Add SHORT_SHA env property with commit short sha
      run: echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV

    - name: Build with Gradle Wrapper
      run: ./gradlew shadowJar
      env:
        BUILD_NUMBER: 'PR-${{ github.event.number }}-${{ env.SHORT_SHA }}'

    - name: Upload build
      uses: actions/upload-artifact@v4.3.3
      with:
        name: 'DeluxeMenus build PR-${{ github.event.number }}-${{ env.SHORT_SHA }}'
        path: build/libs
    - name: Create Release
      if: github.event_name != 'pull_request'
      uses: ncipollo/release-action@v1
      with:
        tag: ${{ env.tag }}
        name: ${{ env.project_id_b }} - ${{ github.run_number }}
        body: |
          This release is automatically compiled by GitHub Actions
          ### Commit Message
          ${{ env.commit_msg }}
        artifacts: build/libs/*.jar
        generateReleaseNotes: true
        prerelease: ${{ env.pre }}
        makeLatest: ${{ env.make_latest }}
        token: ${{ secrets.GITHUB_TOKEN }}
        replacesArtifacts: false
    # NOTE: The Gradle Wrapper is the default and recommended way to run Gradle (https://docs.gradle.org/current/userguide/gradle_wrapper.html).
    # If your project does not have the Gradle Wrapper configured, you can use the following configuration to run Gradle with a specified version.
    #
    # - name: Setup Gradle
    #   uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0
    #   with:
    #     gradle-version: '8.5'
    #
    # - name: Build with Gradle 8.5
    #   run: gradle build

  dependency-submission:

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    # Generates and submits a dependency graph, enabling Dependabot Alerts for all project dependencies.
    # See: https://github.com/gradle/actions/blob/main/dependency-submission/README.md
    - name: Generate and submit dependency graph
      uses: gradle/actions/setup-gradle@v3 # v3.1.0


permissions: write-all
env:
  tag: build-${{ github.ref_name }}-${{ github.run_number }}
  project_id_b: DeluxeMenus-Folia
  commit_id: ${{ github.sha }}
  commit_msg: ${{ github.event.head_commit.message }}
  pre: false
  make_latest: true